# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.
commands:
  install:
    description: Install Ruby within a build. To be used in a Linux distro with Apt
      available.
    parameters:
      version:
        description: Ruby version.
        type: string
    steps:
    - run:
        command: |
          # Determine if sudo is neccessary
          SUDO=""
          if [[ $EUID -ne 0 ]]; then
            SUDO=sudo
          fi

          $SUDO apt-get update && $SUDO apt-get install -y ruby-full
        name: Prep for RVM
    - run:
        command: |
          # Fix for retrieving GPG over IPv6 issue
          mkdir ~/.gnupg && echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf
          curl -sSL https://rvm.io/mpapis.asc | gpg --import -
          curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -

          curl -sSL "https://get.rvm.io" | bash -s stable
          adduser $(whoami) rvm
          source /etc/profile.d/rvm.sh
          rvm install << parameters.version >>
          rvm use << parameters.version >> default

          echo 'source /etc/profile.d/rvm.sh' >> $BASH_ENV
        name: Install Ruby v<< parameters.version >> via RVM
  install-deps:
    description: Install gems with Bundler.
    steps:
    - run: bundle install --path vendor/bundle
  load-cache:
    description: Load cached RubyGems.
    parameters:
      key:
        default: gems-v1
        description: The cache key to use. The key is immutable.
        type: string
    steps:
    - restore_cache:
        keys:
        - << parameters.key >>-{{ checksum "Gemfile.lock"  }}
  run-tests:
    description: Test with RSpec. You have to add `gem 'rspec_junit_formatter'` to
      your Gemfile.
    steps:
    - run: |
        mkdir /tmp/test-results
        TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
        bundle exec rspec $TESTFILES --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        destination: test-results
        path: /tmp/test-results
  save-cache:
    description: Save RubyGems to cache.
    parameters:
      key:
        default: gems-v1
        description: The cache key to use. The key is immutable.
        type: string
    steps:
    - save_cache:
        key: << parameters.key >>-{{ checksum "Gemfile.lock"  }}
        paths:
        - vendor/bundle
description: |
  Common CircleCI tasks for the Ruby programming language. Source: https://github.com/CircleCI-Public/ruby-orb
executors:
  default:
    description: The official CircleCI Ruby Docker image.
    docker:
    - image: circleci/ruby:<< parameters.tag >>
    parameters:
      tag:
        default: latest
        description: The `circleci/ruby` Docker image version tag.
        type: string
version: 2.1