source 'https://rubygems.org'
# Specify your gem's dependencies in jungle_test.gemspec
# gemspec
gem 'csv', '~>3.1.2'
gem 'fileutils', '~>1.4.1'
gem 'rake', '~> 12.0'
gem 'rspec', '~> 3.0'
gem 'rubocop', '~> 0.79.0', require: false
gem 'rubocop-rspec', require: false
